### ISSUE TITLE
GPU install

### ISSUE THREAD

**Issue by fastjack83** [czombos/AMDGPU-XMR-ETH-Mining-Ubuntu#1]
I am trying to use 6 msi rx 570s on miner.  At what point during installation should I connect GPUs to the motherboard with PCIe risers? I’m having trouble booting into Ubuntu when I connect one GPU.

**Comment by czombos** [comment]
The installation works with 1 GPU or more GPUs. Don't forget to turn on the "BIOS" in the "Above 4G decoding" and "PCI Gen 2" settings.
